server:
  port: 20302
spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  configuration:
    # 开启驼峰映射  dept_id => deptId
    map-underscore-to-camel-case: true
  # 实体类简写包别名
  type-aliases-package: top.xiaodashuai.spring2.learndemo.entity